Add var for artful ubuntu (17.10)
naftulikay/ansible-role-rust-dev pull request #6
Opened 2017-11-10 23:34 UTC by Edznux

2017-11-20 01:10 UTC, naftulikay requested changes
Thanks so much for your contribution, and apologies for the delay.

2017-11-20 01:10 UTC, naftulikay commented on vars/ubuntu/artful
> +---
Can you please rename this file to include a `.yml` at the end of the path?

2017-11-20 20:50 UTC, Edznux commented
Ooops, updated !
First time using the ui to do a simple PR, failed it !

2017-11-29 02:39 UTC, naftulikay approved these changes

2017-11-29 02:39 UTC, merged

2017-11-29 02:39 UTC, naftulikay commented
Cutting release 1.0.2 to include this. Thank you for your contribution!